### ISSUE TITLE
[BUG] ImportError When Trying to Import Vision Mamba After Installation

### ISSUE THREAD

**Issue by SiavashShams** [kyegomez/VisionMamba#16]
**Describe the bug**
After successfully installing the vision-mamba package in my environment, attempting to import it using `from vision_mamba.model import Vim` results in an ImportError. The error message indicates a problem with shape mismatch during a matrix multiplication operation in one of the package's dependencies.

**To Reproduce**
1. Attempt to import the Vim class from the package using `from vision_mamba.model import Vim`.

**Additional context**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ss6928/.conda/envs/myenv/lib/python3.10/site-packages/vision_mamba/model.py", line 4, in <module>
    from zeta.nn.modules.ssm import SSM
  File "/home/ss6928/.conda/envs/myenv/lib/python3.10/site-packages/zeta/__init__.py", line 28, in <module>
    from zeta.nn import *
  File "/home/ss6928/.conda/envs/myenv/lib/python3.10/site-packages/zeta/nn/__init__.py", line 3, in <module>
    from zeta.nn.modules import *
  File "/home/ss6928/.conda/envs/myenv/lib/python3.10/site-packages/zeta/nn/modules/__init__.py", line 47, in <module>
    from zeta.nn.modules.mlp_mixer import MLPMixer
  File "/home/ss6928/.conda/envs/myenv/lib/python3.10/site-packages/zeta/nn/modules/mlp_mixer.py", line 145, in <module>
    output = mlp_mixer(example_input)
  File "/home/ss6928/.conda/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ss6928/.conda/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ss6928/.conda/envs/myenv/lib/python3.10/site-packages/zeta/nn/modules/mlp_mixer.py", line 125, in forward
    x = mixer_block(x)
  File "/home/ss6928/.conda/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ss6928/.conda/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ss6928/.conda/envs/myenv/lib/python3.10/site-packages/zeta/nn/modules/mlp_mixer.py", line 63, in forward
    y = self.tokens_mlp(y)
  File "/home/ss6928/.conda/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ss6928/.conda/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ss6928/.conda/envs/myenv/lib/python3.10/site-packages/zeta/nn/modules/mlp_mixer.py", line 30, in forward
    y = self.dense1(x)
  File "/home/ss6928/.conda/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ss6928/.conda/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ss6928/.conda/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (512x4 and 512x512)

**Comment by Darobactin** [comment]
I am faced with the same problem. My environment is pytorch 2.2.2 with cuda 12.1.

**Comment by Lee-jun-young98** [comment]
I solved it after writing this command "pip3 install -U zetascale"

**Comment by kyegomez** [comment]
@SiavashShams try it again now
