### ISSUE TITLE
[BUG] heads is not an argument in Vim

### ISSUE THREAD

**Issue by franeknowak** [kyegomez/VisionMamba#34]
Hi,
I'm simply trying to run the 'Usage' code, but this outputs a traceback:
Traceback (most recent call last):
  File "/home/fnowak/Mamba Reproduction/mamba.py", line 8, in <module>
    model = Vim(
            ^^^^
  File "/home/fnowak/Mamba Reproduction/model.py", line 228, in __init__
    VisionEncoderMambaBlock(
TypeError: VisionEncoderMambaBlock.__init__() got an unexpected keyword argument 'heads'

If I remove heads as an input parameter it runs, but I'm not sure how that influences the model initialisation.
Best,
Franek

**Comment by Allen123321** [comment]
It seems to run fine with 'heads' commented out
```
# Model
model = Vim(
    dim=256,  # Dimension of the transformer model
    #heads=8,  # Number of attention heads
    dt_rank=32,  # Rank of the dynamic routing matrix
    dim_inner=256,  # Inner dimension of the transformer model
    d_state=256,  # Dimension of the state vector
    num_classes=1000,  # Number of output classes
    image_size=224,  # Size of the input image
    patch_size=16,  # Size of each image patch
    channels=3,  # Number of input channels
    dropout=0.1,  # Dropout rate
    depth=12,  # Depth of the transformer model
)




```
